# Generated by Django 4.2.7 on 2023-12-06 12:23

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSwarmCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, null=True)),
                ('last_name', models.CharField(max_length=60, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=12, region='IE')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address1', models.CharField(max_length=60, null=True)),
                ('address2', models.CharField(max_length=60, null=True)),
                ('address3', models.CharField(blank=True, max_length=60, null=True)),
                ('county', models.CharField(max_length=60, null=True)),
                ('eircode', models.CharField(max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('location', models.CharField(choices=[('outside', 'Outside'), ('inside', 'Inside')], max_length=8)),
                ('description', models.TextField(max_length=10000, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
