# Generated by Django 4.2.7 on 2023-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=500)),
                ('details', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('Shown', 'Shown'), ('Hidden', 'Hidden')], default='Shown', max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
